from django.core.management.base import BaseCommand

from jobs.models import FetchSource, Job


DEFAULT_SOURCES = [
    {
        "key": "sabai-job",
        "label": "Sabai Job",
        "domain": "sabaijob.com",
        "feed_url": "https://sabaijob.com/",
        "mode": FetchSource.ModeChoices.MANUAL,
        "enabled": True,
        "requires_manual_url": True,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.BLUE_COLLAR,
        "cadence_value": 30,
        "cadence_unit": FetchSource.CadenceUnit.MINUTES,
        "max_jobs_per_run": 25,
        "status": FetchSource.HealthStatus.WARNING,
        "last_error": "Public website is accessible, but a machine-readable vacancy index was not found yet. Keep manual intake until Sabai Job exposes listing URLs or an API.",
    },
    {
        "key": "jobsdb-th",
        "label": "JobsDB Thailand",
        "domain": "th.jobsdb.com",
        "feed_url": "https://th.jobsdb.com/foreigners-are-welcome-jobs",
        "mode": FetchSource.ModeChoices.HTML,
        "enabled": True,
        "requires_manual_url": False,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.WHITE_COLLAR,
        "cadence_value": 2,
        "cadence_unit": FetchSource.CadenceUnit.HOURS,
        "max_jobs_per_run": 40,
        "status": FetchSource.HealthStatus.HEALTHY,
        "selectors": {
            "__fetch_strategy": "browser",
            "__wait_for": "article[data-automation='normalJob']",
            "entry": "article[data-automation='normalJob']",
            "title": "[data-testid='job-card-title']",
            "company": "[data-automation='jobCompany']",
            "location": "[data-automation='jobCardLocation']",
            "description": "li span",
            "employment_type": "p",
            "image": "img",
            "link": "[data-testid='job-card-title']",
        },
        "last_error": "",
    },
    {
        "key": "jobthai",
        "label": "JobThai",
        "domain": "jobthai.com",
        "feed_url": "https://www.jobthai.com/th/jobs?orderBy=UPDATED_AT_DESC",
        "mode": FetchSource.ModeChoices.HTML,
        "enabled": True,
        "requires_manual_url": False,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.WHITE_COLLAR,
        "cadence_value": 4,
        "cadence_unit": FetchSource.CadenceUnit.HOURS,
        "max_jobs_per_run": 25,
        "status": FetchSource.HealthStatus.HEALTHY,
        "last_error": "",
    },
    {
        "key": "thaingo",
        "label": "ThaiNGO Jobs",
        "domain": "thaingo.org",
        "feed_url": "https://www.thaingo.org/jobs/notexpire",
        "mode": FetchSource.ModeChoices.HTML,
        "enabled": True,
        "requires_manual_url": False,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.NGO,
        "cadence_value": 6,
        "cadence_unit": FetchSource.CadenceUnit.HOURS,
        "max_jobs_per_run": 20,
        "status": FetchSource.HealthStatus.HEALTHY,
        "selectors": {
            "__fetch_strategy": "browser",
            "__wait_for": ".card",
            "entry": ".card",
            "title": ".job-title",
            "company": "p.card-text",
            "description": "p.card-text:nth-of-type(2)",
            "image": "img",
            "link": ".job-title",
        },
        "last_error": "",
    },
    {
        "key": "unjobs-thailand",
        "label": "UN Jobs Thailand",
        "domain": "unjobs.org",
        "feed_url": "https://unjobs.org/duty_stations/thailand",
        "mode": FetchSource.ModeChoices.HTML,
        "enabled": True,
        "requires_manual_url": False,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.NGO,
        "cadence_value": 6,
        "cadence_unit": FetchSource.CadenceUnit.HOURS,
        "max_jobs_per_run": 20,
        "status": FetchSource.HealthStatus.WARNING,
        "selectors": {
            "entry": "a[href*='vacancies/']",
            "title": "",
        },
        "last_error": "",
    },
    {
        "key": "linkedin",
        "label": "LinkedIn",
        "domain": "linkedin.com",
        "feed_url": "",
        "mode": FetchSource.ModeChoices.MANUAL,
        "enabled": True,
        "requires_manual_url": True,
        "auto_publish_website": False,
        "auto_publish_facebook": False,
        "approval_required_for_website": True,
        "approval_required_for_facebook": True,
        "default_category": Job.CategoryChoices.WHITE_COLLAR,
        "cadence_value": 0,
        "cadence_unit": FetchSource.CadenceUnit.HOURS,
        "max_jobs_per_run": 25,
        "status": FetchSource.HealthStatus.WARNING,
        "last_error": "Manual URL intake only.",
    },
]


class Command(BaseCommand):
    help = "Seed default fetch source configurations."

    def handle(self, *args, **options):
        for source_data in DEFAULT_SOURCES:
            source, created = FetchSource.objects.update_or_create(
                key=source_data["key"], defaults=source_data
            )
            status = "created" if created else "updated"
            self.stdout.write(self.style.SUCCESS(f"{source.label}: {status}"))
