upstream dear_career_frontend {
    server frontend:3000;
}

upstream dear_career_backend {
    server backend:8000;
}

server {
    listen 80;
    server_name dear.thureinphyo.com;

    client_max_body_size 10m;

    location /static/ {
        alias /var/www/static/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /media/ {
        alias /var/www/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /api/jobs/ {
        proxy_pass http://dear_career_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /django-admin {
        return 301 /django-admin/;
    }

    location /django-admin/ {
        proxy_pass http://dear_career_backend/admin/;
        proxy_http_version 1.1;
        proxy_redirect /admin/ /django-admin/;
        proxy_set_header X-Forwarded-Prefix /django-admin;
        proxy_set_header Accept-Encoding "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        sub_filter_once off;
        sub_filter_types text/html;
        sub_filter 'href="/admin/' 'href="/django-admin/';
        sub_filter 'action="/admin/' 'action="/django-admin/';
        sub_filter 'value="/admin/' 'value="/django-admin/';
    }

    location / {
        proxy_pass http://dear_career_frontend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
