from django.urls import path

from .views import (
    admin_dashboard_snapshot,
    admin_notification_list,
    admin_notification_mark_read,
    admin_notification_stream,
    facebook_page_posts,
    facebook_publish_job,
    facebook_channel_credential,
    feedback_create,
    fetch_run_list,
    fetch_source_create,
    fetch_source_list,
    fetch_source_run,
    fetch_source_update,
    job_create,
    job_detail,
    job_image_ocr_preview,
    job_image_upload,
    job_list,
    job_scrape_preview,
    managed_ad_create,
    managed_ad_detail,
    managed_ad_list,
    public_active_ad_list,
    visitor_summary,
    visitor_track,
)

urlpatterns = [
    path("", job_list, name="job-list"),
    path("ads/", public_active_ad_list, name="public-ad-list"),
    path("analytics/visit/", visitor_track, name="visitor-track"),
    path("admin/jobs/create/", job_create, name="job-create"),
    path("admin/jobs/scrape/", job_scrape_preview, name="job-scrape-preview"),
    path("admin/jobs/ocr/", job_image_ocr_preview, name="job-image-ocr-preview"),
    path("admin/jobs/<int:job_id>/", job_detail, name="job-detail"),
    path("admin/jobs/<int:job_id>/image/", job_image_upload, name="job-image-upload"),
    path("admin/dashboard/", admin_dashboard_snapshot, name="admin-dashboard-snapshot"),
    path("admin/analytics/visitors/", visitor_summary, name="visitor-summary"),
    path("admin/ads/", managed_ad_list, name="managed-ad-list"),
    path("admin/ads/create/", managed_ad_create, name="managed-ad-create"),
    path("admin/ads/<int:ad_id>/", managed_ad_detail, name="managed-ad-detail"),
    path("admin/channels/facebook/", facebook_channel_credential, name="facebook-channel-credential"),
    path("admin/channels/facebook/posts/", facebook_page_posts, name="facebook-page-posts"),
    path("admin/channels/facebook/publish/", facebook_publish_job, name="facebook-publish-job"),
    path("admin/notifications/", admin_notification_list, name="admin-notification-list"),
    path(
        "admin/notifications/<int:notification_id>/read/",
        admin_notification_mark_read,
        name="admin-notification-mark-read",
    ),
    path("admin/notifications/stream/", admin_notification_stream, name="admin-notification-stream"),
    path("feedback/", feedback_create, name="feedback-create"),
    path("admin/sources/", fetch_source_list, name="fetch-source-list"),
    path("admin/sources/create/", fetch_source_create, name="fetch-source-create"),
    path("admin/sources/<int:source_id>/", fetch_source_update, name="fetch-source-update"),
    path("admin/sources/<int:source_id>/run/", fetch_source_run, name="fetch-source-run"),
    path("admin/runs/", fetch_run_list, name="fetch-run-list"),
]
