# Generated by Django 6.0.2 on 2026-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="SEO အတြက္ URL friendly name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description_mm", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scraper", "Scraper")],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "source_job_id",
                    models.CharField(
                        blank=True,
                        help_text="Original website က job ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                        ],
                        default="full-time",
                        max_length=50,
                    ),
                ),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_fb_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Facebook မွာ တင္ၿပီး/မတင္ရေသး",
                    ),
                ),
                (
                    "fb_post_id",
                    models.CharField(
                        blank=True,
                        help_text="Facebook post ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="jobs_job_slug_idx"),
                    models.Index(fields=["source"], name="jobs_job_source_idx"),
                    models.Index(
                        fields=["source_job_id"], name="jobs_job_source_job_id_idx"
                    ),
                ],
            },
        ),
    ]
