# Generated by Django 6.0.2 on 2026-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_slug_9562d1_idx',
            old_name='jobs_job_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_source_e2155e_idx',
            old_name='jobs_job_source_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_source__d36421_idx',
            old_name='jobs_job_source_job_id_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='is_fb_posted',
            field=models.BooleanField(default=False, help_text='Facebook မှာ တင်ပြီး/မတင်ရသေး'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(help_text='SEO အတွက် URL friendly name', max_length=255, unique=True),
        ),
    ]
