# Generated by Django 6.0.2 on 2026-03-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('published_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FetchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=255)),
                ('feed_url', models.URLField(blank=True)),
                ('mode', models.CharField(choices=[('html', 'HTML'), ('rss', 'RSS'), ('manual', 'Manual')], default='html', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_manual_url', models.BooleanField(default=False)),
                ('auto_publish_website', models.BooleanField(default=True)),
                ('auto_publish_facebook', models.BooleanField(default=False)),
                ('approval_required_for_website', models.BooleanField(default=False)),
                ('approval_required_for_facebook', models.BooleanField(default=True)),
                ('default_category', models.CharField(choices=[('ngo', 'NGO'), ('white-collar', 'White Collar'), ('blue-collar', 'Blue Collar')], default='white-collar', max_length=50)),
                ('cadence_value', models.PositiveIntegerField(default=30)),
                ('cadence_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], default='minutes', max_length=20)),
                ('max_jobs_per_run', models.PositiveIntegerField(default=25)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('paused', 'Paused')], default='healthy', max_length=20)),
                ('selectors', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='requires_facebook_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='requires_website_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('pending-review', 'Pending Review')], default='published', max_length=32),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx'),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.fetchsource'),
        ),
    ]
