# Generated by Django 6.0.2 on 2026-03-02 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('eyebrow', models.CharField(blank=True, default='Sponsored', max_length=60)),
                ('description', models.TextField()),
                ('cta_label', models.CharField(default='Learn more', max_length=60)),
                ('href', models.URLField()),
                ('placement', models.CharField(choices=[('jobs-inline', 'Jobs inline'), ('jobs-detail', 'Job detail'), ('jobs-search', 'Jobs search')], default='jobs-inline', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'sort_order', 'title'],
                'indexes': [models.Index(fields=['placement'], name='jobs_manage_placeme_12d7b0_idx'), models.Index(fields=['status'], name='jobs_manage_status_724a2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=160)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['visit_date'], name='jobs_visito_visit_d_180d77_idx'), models.Index(fields=['path'], name='jobs_visito_path_a6ead1_idx'), models.Index(fields=['session_key'], name='jobs_visito_session_2dec48_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'path', 'visit_date'), name='jobs_visitor_event_unique_session_path_date')],
            },
        ),
    ]
