# Generated by Django 6.0.2 on 2026-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcredential',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='channelcredential',
            name='profile_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
