# Generated by Django 6.0.2 on 2026-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_adminnotification_read_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminnotification',
            new_name='jobs_adminn_read_at_7827a0_idx',
            old_name='jobs_adminn_read_at_08d8f6_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='image_file',
            field=models.FileField(blank=True, upload_to='jobs/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
