# Generated by Django 6.0.2 on 2026-03-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_rename_jobs_adminn_read_at_08d8f6_idx_jobs_adminn_read_at_7827a0_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_title", models.CharField(max_length=255)),
                ("job_company", models.CharField(blank=True, max_length=255)),
                ("job_location", models.CharField(blank=True, max_length=255)),
                ("job_slug", models.SlugField(blank=True, max_length=255)),
                ("reporter_name", models.CharField(blank=True, max_length=120)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("scam", "Scam / fake job"),
                            ("inaccurate", "Inaccurate information"),
                            ("expired", "Expired / closed role"),
                            ("duplicate", "Duplicate posting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("reviewed", "Reviewed"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status"], name="jobs_jobrep_status_2df4f5_idx"), models.Index(fields=["created_at"], name="jobs_jobrep_created_2a8da8_idx")],
            },
        ),
    ]
