# Generated by Django 6.0.2 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_channelcredential_app_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedad",
            name="placement",
            field=models.CharField(
                choices=[
                    ("home-hero", "Home hero"),
                    ("jobs-inline", "Jobs inline"),
                    ("jobs-detail", "Job detail"),
                    ("jobs-search", "Jobs search"),
                ],
                default="jobs-inline",
                max_length=40,
            ),
        ),
    ]
