# Generated by Django 6.0.2 on 2026-03-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobalertsubscriber_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobreport',
            new_name='jobs_jobrep_status_bb6de2_idx',
            old_name='jobs_jobrep_status_2df4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='jobreport',
            new_name='jobs_jobrep_created_083266_idx',
            old_name='jobs_jobrep_created_2a8da8_idx',
        ),
    ]
